version: "3"

services:
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-network
    restart: always
  
  app:
    build:
      context: ./app
    entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    container_name: app
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - database
    networks:
      - fullcycle-network
    tty: true

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    depends_on:
      - app

networks:
  fullcycle-network:
    driver: bridge
